# DB Configuration
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/sample
  username: root
  password: 1234
 jpa: 
  hibernate.ddl-auto: update
  show-sql: true
 user.datasource.driver-class-name: com.mysql.jdbc.Driver
user.oauth.clientId: client
user.oauth.clientSecret: secret

user.oauth.user.username: user
user.oauth.user.password: pass
user.oauth.accessTokenValidity: 3600
user.oauth.refreshTokenValidity: 21600
security.oauth2.resource.filter-order: 3